### ISSUE TITLE
Challenge with lists.js and map.js for restaurants.map to restaurant

### ISSUE THREAD

**Issue by benjaminmateev** [sjwinther/techvaernet-restaurants#1]
Hey friends, 

this is Benjamin from Berlin. I stumbled onto this awesome project via Sissel, she told me about it and we don't have something like this in Berlin yet but I am helping a friend with a restaurant to set up an online shop and thought a central page with all restaurants mapped would be amazing for Berlin too. 

As you made this open-source I would love to reuse the code base and make some change to the design and refer to your awesome project! 

But I am having a challenge, somehow fetching the results from Airtable and displaying them does not quite work yet. From the debugger tools, I know that fetching works, and the props are filled with the two restaurants that I have in my table so far but they are not being rendered on the page and I researched how next.js does it and I cannot see a reason why it should work. In particular here 

```
<ul className="flex flex-wrap -m-3">
                {restaurants.map(restaurant => {
                  if (
                    restaurant.display &&
                    restaurant.name &&
                    restaurant.description &&
                    restaurant.url
                  )
                    return (
                      <ListItem key={restaurant.name} restaurant={restaurant} />
                    ) 
                })}
              </ul>
```

the ul tag is still rendered but it seems that the restaurants.map somehow is where it stops working. If I debug in the chrome developer tools and I get one of the restaurants through the props, I can see that display, name, description and URL are filled. And given it's rendering the ul-tag restaurants and restaurants.lenght are also not zero and true.

I cannot quite get why it is not rendering. Can you help me? You can check the current status on [dineinberlin.com](dineinberlin.com), its deployed via Zeit.

Again amazing work, I really love the simplicity of the project from a design and code perspective!

Stay safe and healthy!
Ben

**Comment by benjaminmateev** [comment]
Figured it out, my columns in Airtable were uppercase, and the attributes in code lower case, that was the issue!

**Comment by sjwinther** [comment]
Hey @benjaminmateev! Sorry for not getting back sooner. Happy to hear you figured it out though. The Berlin project is looking good! Do let me know if you need help with anything else. I've updated the list view with some filters as well, if you want to take a look.

**Comment by benjaminmateev** [comment]
No worries, it was a stupid mistake anyway. 

I started working on filters, this is awesome! I will try to rebase my master with yours and add them for sure. I was also thinking about adding neighbourhoods as well and let people filter on the map for that. Happy to contribute once I am making progress!

Do you use a webhook to redeploy to Zeit when you update the Airtable base or do you redeploy manually?

**Comment by sjwinther** [comment]
Neighbourhoods is a great idea! Are you thinking about adding it to the form, or inferring it from the address somehow?

Currently redeploy manually actually, which is ... not the best solution. Zeit offers a thing called Deploy Hooks, but they need to you sign up with GitHub to do it, which I'm not super keen on doing. Let me know if you find a good solution :)

**Comment by benjaminmateev** [comment]
I am thinking of getting a webhook into place, will experiment a little bit with Zapier and see whether ew can connect a new entry to Airtable to posting to a deploy hook URL of zeit.co. That way deployment should work well.

I am a bit torn on neighbourhoods, whether to use them for where a place is or where they are delivering to since a lot of place in Berlin only deliver in a certain vicinity.  But some also just draw a circle on the map and said, we deliver in this circle (probably a radius of 2km or so) so maybe focus on better filters for searching the list and map views. What comes to mind is, that the list view is getting very big with now more than 100 restaurants on it. And it does not feel great that the latest entries are always at the bottom. So filtering by neighbourhood there might be good and maybe for the unfiltered list view, we could randomize it in some way to mix the results up a bit (though what happens to expectations when people go on there). A bit torn here as well, haha.

What do you think?

**Comment by benjaminmateev** [comment]
I am adding neighbourhoods now and will do a dropdown for Berlin and a filter on the list view. Seems like the most reasonable one to make the list view a bit more usable with many entries.

**Comment by sjwinther** [comment]
> I am adding neighbourhoods now and will do a dropdown for Berlin and a filter on the list view. Seems like the most reasonable one to make the list view a bit more usable with many entries.

Agreed! Are you adding to Airtable form as well, or inferring it from address?

Oh, and neighbourhoods definitely makes the most sense for Copenhagen as well, as it's so small that most places deliver to the whole city. So would love to see this :)

Maybe shuffling the array before showing it on the list could be fun? 😅 So the first restaurants don't get all the views ...

**Comment by benjaminmateev** [comment]
I think adding to the form tbh, not sure how I would infer it from address because the neighbourhood model in Berlin is also not very straight forward 😂

I think its gonna be as simple as replicating the offerings logic and adding that filter to the lists view.

I was thinking about shuffle as well, I should just do that for a starter, haha

**Comment by sjwinther** [comment]
Perfect. Feel free to add a PR to the original repo, when you've added it. The CPH project could use it as well.

**Comment by benjaminmateev** [comment]
I started working on it, I think it should be working but somehow it does not yet, still trying to figure out why though - 

https://github.com/benjaminmateev/dineinberlin/pull/3

I cant add at PR from my fork as I made changes to master that appear in a PR unfortunately but I can try to replicate the change in a local clone of dinecph and then create a PR based on that.

**Comment by sjwinther** [comment]
Sorry for being slow on the draw – but it looks like you got it working? :)

**Comment by benjaminmateev** [comment]
Yes, actually figured it out, and now it is doing quite well. Shuffling only on reload, filter both offers and neighbourhoods. 

Actually deploying it now with some friends in Lima, Peru today and tomorrow
